server:
  port: 8080
  contextPath: /SpringBootApp
#---
spring:
  profiles: local,default
  h2:
    console:
      enabled: true
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
#---
